blank_issues_enabled: false
contact_links:
  - name: Homebridge-Honeywell-Home - Issues
    url: https://github.com/donavanbecker/homebridge-honeywell-home/issues
    about: Please ask and answer questions here.
  - name: Homebridge-Honeywell-Home - Pull Requests
    url: https://github.com/donavanbecker/homebridge-honeywell-home/pulls
    about: Please report security vulnerabilities here.
