name: Changelog

on: [push]

jobs:
  autocommit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: teaminkling/skip-commit@master
        with:
          commit-filter: skip-log, skip-ci, automated
      - uses: teaminkling/autologger@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repository: ${{ donavanbecker.homebridge-honeywell-home }}
      - name: Pre-remote commit actions
        run: |
          git add CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "[skip-log, auto] Make changes automatically to meta files."
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
